name: custom work flow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      -master
  workflow_dispatch:

jobs:     
  readfilecontent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: file_operations
        run: |
          pwd
          ls -la
          cat file1
